- name: install dotfiles
  git: repo=git@github.com:azusa-kikuike/dotfiles.git dest=~/projects/dotfiles

- name: copy .vimrc
  copy: src=~/projects/dotfiles/.vimrc dest=~/.vimrc owner="{{ user }}" group=staff mode=0644

- name: copy .zshrc
  copy: src=~/projects/dotfiles/.zshrc dest=~/.zshrc owner="{{ user }}" group=staff mode=0644

- name: copy .tmux.conf
  copy: src=~/projects/dotfiles/.tmux.conf dest=~/.tmux.conf owner="{{ user }}" group=staff mode=0644

- name: copy .gitconfig
  copy: src=~/projects/dotfiles/.gitconfig dest=~/.gitconfig owner="{{ user }}" group=staff mode=0644

- name: copy .gitignore
  copy: src=~/projects/dotfiles/.gitignore dest=~/.gitignore owner="{{ user }}" group=staff mode=0644

- name: copy .gemrc
  copy: src=~/projects/dotfiles/.gemrc dest=~/.gemrc owner="{{ user }}" group=staff mode=0644
