- name: brew update
  shell: brew update
- name: brew upgrade
  shell: brew upgrade
- name: mkdir ~/bin
  file: path=~/bin state=directory
- name: mkdir ~/logs
  file: path=~/logs state=directory
- name: copy script for brew upgrade
  template: src=brew_update.sh dest=~/bin/brew_update.sh owner=azusa group=staff mode=0644
- name: launchctl
  shell: launchctl load jp.azusa.brew.plist
